name: Android Fastlane with Firebase App Distribution Workflow

on:
  push:
    branches:
      - main

jobs:
  distribute_to_firebase:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout my repo code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.3'
          channel: stable

      - name: Install Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.4'
          bundler-cache: true
          working-directory: android

      - name: Add Linux platform to Bundler
        run: bundle lock --add-platform x86_64-linux
        working-directory: android

      - name: Install Fastlane dependencies
        run: |
          bundle install || gem install fastlane
        working-directory: android

      - name: Clean Flutter Project
        run: flutter clean

      - name: Get Flutter Dependencies
        run: flutter pub get

      - name: Build APK manually
        run: flutter build apk --release --no-tree-shake-icons

      - name: Distribute App to Firebase
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: fastlane android firebase_distribution
        working-directory: android
